import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { DatabaseService } from '../../common/database.service';
@Injectable()
export class MenusService {
 constructor(private readonly db:DatabaseService){}
 private async next(client:any, code:string){ const r=await client.query(`UPDATE core.business_sequences SET current_value=current_value+1,updated_at=NOW() WHERE sequence_code=$1 RETURNING current_value,prefix,padding`,[code]); if(!r.rows[0]) throw new Error(`${code} sequence missing`); return `${r.rows[0].prefix}${String(r.rows[0].current_value).padStart(r.rows[0].padding,'0')}`; }
 async createDish(input:any){ return this.db.transaction(async c=>{ const dishCode=await this.next(c,'DISH'); const recipeCode=await this.next(c,'RECIPE'); const dishId=randomUUID(); const recipeId=randomUUID(); await c.query(`INSERT INTO menu.dishes(id,dish_code,name,description,category_code,image_url,shelf_life_hours,status_code) VALUES($1,$2,$3,$4,$5,$6,$7,'ACTIVE')`,[dishId,dishCode,input.name.trim(),input.description??null,input.categoryCode??null,input.imageUrl??null,input.shelfLifeHours]); await c.query(`INSERT INTO menu.recipe_versions(id,recipe_code,dish_id,version_number,yield_quantity,yield_unit,estimated_cost,status_code,approved_at) VALUES($1,$2,$3,1,$4,$5,$6,'APPROVED',NOW())`,[recipeId,recipeCode,dishId,input.yieldQuantity,input.yieldUnit,input.estimatedCost]); return {success:true,data:{dishCode,recipeCode},meta:{timestamp:new Date().toISOString()}}; }); }
 async createMenu(input:any){ return this.db.transaction(async c=>{ const cpp=await c.query(`SELECT c.id,c.market_id FROM operations.cpp c WHERE c.cpp_code=$1 AND c.status_code='ACTIVE'`,[input.cppCode]); if(!cpp.rows[0]) throw new NotFoundException('CPP_NOT_FOUND'); const code=await this.next(c,'MENU'); await c.query(`INSERT INTO menu.weekly_menus(id,menu_code,market_id,cpp_id,starts_on,ends_on,order_cutoff_at,message) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),code,cpp.rows[0].market_id,cpp.rows[0].id,input.startsOn,input.endsOn,input.orderCutoffAt??null,input.message??null]); return {success:true,data:{menuCode:code,status:'DRAFT'},meta:{timestamp:new Date().toISOString()}}; }); }
 async addItem(menuCode:string,input:any){ return this.db.transaction(async c=>{ const m=await c.query(`SELECT id,starts_on,ends_on,status_code FROM menu.weekly_menus WHERE menu_code=$1 FOR UPDATE`,[menuCode]); if(!m.rows[0]) throw new NotFoundException('MENU_NOT_FOUND'); if(m.rows[0].status_code!=='DRAFT') throw new ConflictException('MENU_NOT_EDITABLE'); if(input.serviceDate<m.rows[0].starts_on.toISOString().slice(0,10)||input.serviceDate>m.rows[0].ends_on.toISOString().slice(0,10)) throw new BadRequestException('SERVICE_DATE_OUTSIDE_MENU'); const d=await c.query(`SELECT d.id,r.id recipe_id FROM menu.dishes d JOIN menu.recipe_versions r ON r.dish_id=d.id AND r.status_code='APPROVED' WHERE d.dish_code=$1 AND d.is_active=TRUE ORDER BY r.version_number DESC LIMIT 1`,[input.dishCode]); if(!d.rows[0]) throw new NotFoundException('DISH_NOT_FOUND'); await c.query(`INSERT INTO menu.weekly_menu_items(id,weekly_menu_id,dish_id,recipe_version_id,service_date,presentation_name,price,capacity) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[randomUUID(),m.rows[0].id,d.rows[0].id,d.rows[0].recipe_id,input.serviceDate,input.presentationName,input.price,input.capacity]); return {success:true,data:{menuCode},meta:{timestamp:new Date().toISOString()}}; }); }
 async publish(menuCode:string){ return this.db.transaction(async c=>{ const m=await c.query(`SELECT id,cpp_id,starts_on,ends_on,status_code FROM menu.weekly_menus WHERE menu_code=$1 FOR UPDATE`,[menuCode]); if(!m.rows[0]) throw new NotFoundException('MENU_NOT_FOUND'); const count=await c.query(`SELECT COUNT(*)::int count FROM menu.weekly_menu_items WHERE weekly_menu_id=$1 AND status_code='AVAILABLE'`,[m.rows[0].id]); if(Number(count.rows[0].count)<1) throw new BadRequestException('MENU_HAS_NO_ITEMS'); await c.query(`UPDATE menu.weekly_menus SET status_code='PUBLISHED',published_at=NOW(),updated_at=NOW(),version=version+1 WHERE id=$1`,[m.rows[0].id]); return {success:true,data:{menuCode,status:'PUBLISHED'},meta:{timestamp:new Date().toISOString()}}; }); }
 async currentForHousehold(haid:string){ const r=await this.db.query(`SELECT wm.menu_code,wm.starts_on,wm.ends_on,wm.order_cutoff_at,wm.message,c.cpp_code,z.zone_code,d.dish_code,d.name,d.description,d.image_url,i.service_date,i.presentation_name,i.price,i.capacity-i.reserved_quantity-i.sold_quantity available_quantity FROM household.households h JOIN household.locations l ON l.household_id=h.id AND l.is_primary=TRUE AND l.is_active=TRUE JOIN territory.location_coverage lc ON lc.location_id=l.id AND lc.status_code='ACTIVE' JOIN operations.cpp c ON c.id=lc.cpp_id JOIN territory.service_zones z ON z.id=lc.zone_id JOIN menu.weekly_menus wm ON wm.cpp_id=c.id AND wm.status_code='PUBLISHED' AND CURRENT_DATE BETWEEN wm.starts_on AND wm.ends_on JOIN menu.weekly_menu_items i ON i.weekly_menu_id=wm.id AND i.status_code='AVAILABLE' JOIN menu.dishes d ON d.id=i.dish_id WHERE h.haid=$1 AND h.is_active=TRUE ORDER BY i.service_date,d.name`,[haid]); if(!r.rows.length) return {success:true,data:null,meta:{timestamp:new Date().toISOString()}}; const x=r.rows[0]; return {success:true,data:{menuCode:x.menu_code,startsOn:x.starts_on,endsOn:x.ends_on,orderCutoffAt:x.order_cutoff_at,message:x.message,cppCode:x.cpp_code,zoneCode:x.zone_code,items:r.rows.map((q:any)=>({dishCode:q.dish_code,name:q.name,description:q.description,imageUrl:q.image_url,serviceDate:q.service_date,presentationName:q.presentation_name,price:Number(q.price),availableQuantity:Number(q.available_quantity)}))},meta:{timestamp:new Date().toISOString()}}; }
}
